import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/components/layout/Nav";
import ReduxProvider from "@/redux/provider/ReduxProvider";
import TopContactSection from "@/components/layout/TopContactSection";
import Footer from "@/components/layout/Footer";
import "primereact/resources/themes/lara-light-cyan/theme.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "K B Touch – Your Signature in Beauty",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <TopContactSection />
          <Nav />
          <div className="flex justify-center sm:px-4">
            <div className="w-full max-w-[1400px]">{children}</div>
          </div>
        </body>
      </html>
      <Footer />
    </ReduxProvider>
  );
}
